{% set version = "4.4.4" %}

package:
  name: pywps
  version: {{ version }}

source:
  url: https://github.com/geopython/pywps/archive/{{ version }}.tar.gz
  sha256: a942866dad1c50ccf6d624090e147d733dec417da5971ee0c56b64c0cdd2f5a0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - owslib
    - jsonschema
    - lxml
    - werkzeug
    - sqlalchemy
    - python-dateutil
    - requests
    - jinja2
    - humanize

test:
  imports:
    - pywps

about:
  home: http://pywps.org/
  license: MIT
  license_file: LICENSE.txt
  summary: PyWPS (Python Web Processing Service) is an implementation of the Web processing Service standard from Open Geospatial Consortium.

extra:
  recipe-maintainers:
    - Zeitsperre
    - huard
    - cehbrecht
