{% set version = "4.2.2" %}

package:
  name: pywps
  version: {{ version }}

source:
  url: https://github.com/geopython/pywps/archive/{{ version }}.tar.gz
  sha256: 83098a1fb72f28b6fe775c624e0c2dd3cbc077e3f2c04ae805eedb9e91365098

build:
  number: 0
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - owslib
    - jsonschema
    - lxml
    - werkzeug
    - sqlalchemy
    - python-dateutil
    - requests
    - jinja2
    - pathlib
    - flufl.enum  # [py27]

test:
  imports:
    - pywps

about:
  home: http://pywps.org/
  license: MIT
  license_file: LICENSE.txt
  summary: 'PyWPS (Python Web Processing Service) is an implementation of the Web processing Service standard from Open Geospatial Consortium.'

extra:
  recipe-maintainers:
    - cehbrecht
