{% set version = "4.5.2" %}

package:
  name: pywps
  version: {{ version }}

source:
  url: https://github.com/geopython/pywps/archive/{{ version }}.tar.gz
  sha256: e40995eb3d684ec233bc19aa63b2433af73bd81003eabdacb79fde170af1f33f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.7
    - docutils
    - fiona
    - humanize
    - jinja2
    - jsonschema
    - lxml
    - markupsafe
    - owslib
    - python-dateutil
    - python-geotiff
    - requests
    - sphinx
    - sqlalchemy
    - werkzeug

test:
  imports:
    - pywps

about:
  home: http://pywps.org/
  license: MIT
  license_file: LICENSE.txt
  summary: PyWPS (Python Web Processing Service) is an implementation of the Web processing Service standard from Open Geospatial Consortium.

extra:
  recipe-maintainers:
    - Zeitsperre
    - huard
    - cehbrecht
