{% set version = "4.2.10" %}

package:
  name: pywps
  version: {{ version }}

source:
  url: https://github.com/geopython/pywps/archive/{{ version }}.tar.gz
  sha256: a7613b343816df45fd2fa44e8a450f52bbd87b3356f370d04eddde022659d356

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - owslib
    - jsonschema
    - lxml
    - werkzeug
    - sqlalchemy
    - python-dateutil
    - requests
    - jinja2
    - pathlib
    - flufl.enum  # [py27]

test:
  imports:
    - pywps

about:
  home: http://pywps.org/
  license: MIT
  license_file: LICENSE.txt
  summary: PyWPS (Python Web Processing Service) is an implementation of the Web processing Service standard from Open Geospatial Consortium.

extra:
  recipe-maintainers:
    - cehbrecht
