{% set version = "4.6.0" %}

package:
  name: pywps
  version: {{ version }}

source:
  url: https://github.com/geopython/pywps/archive/{{ version }}.tar.gz
  sha256: 7aeb749d788fa7795fb0fe76ee76096a4606251f56fa211e4d72b8fc7b7323a2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - docutils
    - fiona
    - humanize
    - jinja2
    - jsonschema
    - lxml
    - markupsafe
    - owslib
    - python-dateutil
    - python-geotiff
    - requests
    - sphinx
    - sqlalchemy
    - werkzeug

test:
  imports:
    - pywps
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: http://pywps.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PyWPS (Python Web Processing Service) is an implementation of the Web processing Service standard from Open Geospatial Consortium.
  doc_url: https://pywps.org/
  dev_url: https://github.com/geopython/PyWPS

extra:
  recipe-maintainers:
    - Zeitsperre
    - huard
    - cehbrecht
