appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: c9OCnEUbiJWXt5MgikgJEaYCvgWq3uq1mZLdloy4Zl/mW0AyCtXKOSjc/hfzsWIE69w6SK5AMqfcYm7jsSY9P/nKvgLWUhs3AEWmCiH1ceVG16/M9LlkrZuXvQ39wu3KmIgt33Sw2du2HuEyeNOg+2opTCeSqduPygMznTtVfKDAtEpMqvFmZ6B0XkQgx6WbjZbNLRoerM0qK+KHfVKqM45dGsvXyNquIvFsItOVbcvT5Ymmy42QfIBW8Cw+DJqwIqePjoj+qdB05PYo5BMvIsVPgoHwKHqd0GZFwbs8bbOG6G8PflovBBInkk/YahVMXK0lJJaaIWPk8YfX17pc24dJn70u/0mFqW9yfP97OYHqQwWCN2s1GRAVFcpI7s2FFDAALLHOdKH8IqzOQarOq8cHtqPCc0GkKT3LbPzS77h60P6e7ZAog/fmdo766NRBuxkPVBLggh+uNZVWrkeubP+pI2G7pe07RwvqWj3/6CygAWNjILPjUDrj9CXX34gDA+PtE5v2/uWFfwmc7fMO95mf6U4vMiY20YqtVQCwwV9lrL6OI6I80yHjrd6K2l0CBEr6SvjXiqt8NNKkRn1KW5UE7U0Bb8N3VXvtqwUPlMmBVt3GOg1bc7yxc7uBN4PHwrG4SGIzv8Y2WsShz2TCIAUMRsnYAJvqo6QwWhEfHNU=}
